### ISSUE TITLE
Please add support for recent versions of tls

### ISSUE THREAD

**Issue by peti** [enzoh/smtps-gmail#10]
http://packdeps.haskellers.com/feed?needle=smtps-gmail

**Comment by nikita-volkov** [comment]
:+1:

**Comment by jcristovao** [comment]
I'll second nikita-volkov request, if his patch could be merged and this would reach hackage it would be great!
Thanks

**Comment by enzoh** [comment]
Sorry for the late response. I have accepted the changes and pushed the latest to Hackage.
