### ISSUE TITLE
Stopped working with gmail.com

### ISSUE THREAD

**Issue by tittoassini** [enzoh/smtps-gmail#14]
Since a few days,  while trying to send mail to a gmail.com address, I get:

ParseError "Expected SMTP reply code \"250\", but recieved SMTP reply code \"501\"."

Maybe the gmail servers have become stricter in their syntax checks?

* 501	Syntax error in parameters or arguments

**Comment by andrewthad** [comment]
I'm getting this error as well.

**Comment by enzoh** [comment]
@tittoassini @andrewthad Just pushed a fix. Please fetch the latest from Hackage. Regards,
